apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: clou-disk # name like we had ealier "demostorage"
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain  # Default is Delete, recommended is retain
volumeBindingMode: WaitForFirstConsumer # Default is Immediate, recommended is WaitForFirstConsumer
allowVolumeExpansion: true 
parameters:
  skuName: Standard_LRS
  location: centralindia
