apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pvc1
spec:
 storageClassName: mylocal #this needs to change
 #storageClassName: localstorage #uncomment this 
 #and comment the above adte experiment 
 accessModes:
 - ReadWriteMany
 resources:
  requests:
   storage: "1Gi"
