apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp-new
spec:
 selector:
  matchLabels:
   app: new
 replicas: 3
 template:
  metadata:
   labels:
    app: new
  spec:
   containers:
   - name: prod-app
     image: quay.io/gauravkumar9130/production:v2
