apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp-new
spec:
 selector:
  matchLabels:
   app: myapp
 replicas: 1
 template:
  metadata:
   labels:
    app: myapp
  spec:
   containers:
   - name: prod
     image: quay.io/gauravkumar9130/production:v2
