apiVersion: apps/v1
kind: Deployment
metadata:
  name: probeapp
  labels:
    app: probeapp
spec:
  replicas: 1  # Set to 3 replicas for scaling
  selector:
    matchLabels:
      app: probeapp
  template:
    metadata:
      labels:
        app: probeapp
    spec:
      containers:
      - name: container
        image: sagarkp/probe_app:1.1  # Local image built in Minikube
        ports:
        - containerPort: 8080

        # Liveness Probe: Checks /healthz every 5 seconds after an initial delay of 5 seconds
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 5

        # Readiness Probe: Checks /readyz every 5 seconds after an initial delay of 10 seconds
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 5
          failureThreshold: 5

        # Startup Probe: Waits for /healthz to become available within 10 checks (50 seconds total)
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 20

---
apiVersion: v1
kind: Service
metadata:
  name: probeappservice
spec:
  selector:
    app: probeapp  # Ensures the Service routes traffic to Pods with this label
  ports:
    - port: 80           # Expose on port 80 (external port)
      targetPort: 8080   # Directs traffic to container port 8080
  type: LoadBalancer     # LoadBalancer Service for external access

